### ISSUE TITLE
Fix incorrect hand scale / position

### ISSUE THREAD

**Issue by jonjhiggins** [uwe-xr-ma-2023/handu#45]
On hammerhead headset: scale is incorrect
On 3D printed headset: scale and position incorrect

Looks like we will need different settings for the Ultraleap service provider for each headset......?

**Comment by jonjhiggins** [comment]
Hey @marcingawin can you fix up the camera tracking please. Its different on each headset because of the different camera mounts.

The process is to load the app `PicoARAlignment` on each headset, tweak the settings until the virtual hand is the desired size and position (Tosin suggested oversizing the virtual hands).

Then the values are entered on the `MainSceneManager` in Unity (I can show you where)

**Comment by marcingawin** [comment]
To be done for another headset

**Comment by jonjhiggins** [comment]
Looks like the hammerhead headset tracking may have got worse for me?

The values were adjusted in this commit https://github.com/uwe-xr-ma-2023/handu/commit/14351942f7f6addf53768a87eae7ab0c11ff7e37 , was that an intentional change?

**Comment by marcingawin** [comment]
Camera tracking adjusted for both headsets - the scale is still too small

**Comment by jonjhiggins** [comment]
WONTFIX

We weren't able to increase the outer scale of the hands, the methods available on the hand binder UI seemed to enlarge parts of the hand. I thought we would be able to resolve with the PicoARAlignment app but changing the hand scale on that just affected the distance of the hand from user, we found that out too late in the project to resolve in time
